### ISSUE TITLE
Desktop icons for mounted volumes pile on top of other icons

### ISSUE THREAD

**Issue by direwolfie** [mate-desktop/mate-desktop#218] opened 2016-03-24 12:24 UTC
Hello!

When mounting volumes (other partitions, usb drives, etc) for the first time, the icons of mounted volumes appear correctly after all the other icons on the desktop. 
![](https://storage7.static.itmages.com/i/16/0324/h_1458821647_6683309_0a78f1e93f.png).
But when the same device is plugged in the second time - the icons of the mounted volumes appear in the same place they appeared the first time and they pile on top of other desktop icons.  ![](https://storage5.static.itmages.com/i/16/0324/s_1458821702_4449199_17ce088513.png).  ![](https://storage8.static.itmages.com/i/16/0324/s_1458821726_6451290_2c59743d11.png).
This creates a bit of a mess.

I am running Linux Mint 17.2 with MATE 1.10.2.
Same issue on Linux Mint Debian Edition 2 with MATE 1.12.0.
##

**Comment by flexiondotorg** [comment] 2017-01-17 11:18
Duplicate of #228

**Closed by flexiondotorg** 2017-01-17 11:18 UTC
