### ISSUE TITLE
Alt+F4 to kill an app sometimes turns screensaver on

### ISSUE THREAD

**Issue by LiamDawe** [mate-desktop/mate-desktop#198] opened 2015-08-24 16:14 UTC
Not sure why this is happening, but sometimes force killing an app with ALT+F4 activates the lock screen and screensaver?

**Comment by monsta** [comment] 2016-03-04 11:15
We can't reproduce this at all. Does it still happen in 1.12?

**Comment by monsta** [comment] 2016-03-25 12:39
If it doesn't happen in the latest version, we'll close this as fixed.

**Closed** 2016-04-24 10:44 UTC
Labels: unconfirmed
