### ISSUE TITLE
Most Infra Red Remote commands not being passed via DE?

### ISSUE THREAD

**Issue by tonyabc** [mate-desktop/mate-desktop#348] opened 2019-01-04 20:26 UTC
#### Expected behaviour
This has been working fully and without any issues until around the end of November when it stopped working fully

If I press a button mapped via rc_keymaps on my remote it should be passed via the DE to the app correctly - App in this instance is either mythfrontend or kodi or vlc

#### Actual behaviour
Some buttons do work as they are meant to, however the bulk are just 'disappearing' with no throughput.

#### Steps to reproduce the behaviour
Install v4l utils, depending on your distro install say a valid rc6_mce keymapping file in /etc/rc_keymaps (this should work for rc6_mce type infra red remotes, obviously if your remote is different then install the appropriate file).  Install key-mon.

Open two terminal sessions:-

In one of them run 'key-mon' which should open a GUI that shows you which keyboard or mouse feature is being used.

In the second terminal session run 'ir-keytable -t' which should read directly from the appropriate input port for the infra red remote and show you which buttons are being pressed (hex) and what the appropriate keymapped output being generated is.

While running both apps onscreen at the same time hit some buttons on your remote...

'ir-keytable -t' will show you ALL the button presses and what they should be generating.

However the simultaneous output from 'key-mon' only shows some of the button presses and the majority do not seem to be being passed to the DE.

In effect 'something' is either intercepting or cancelling the missing keypresses getting passed.

#### MATE general version
1.20.4

#### Package version

mate-desktop-1.20.4-1.fc29.x86_64

#### Linux Distribution

Fedora 29 x64

#### Link to downstream report of your Distribution
https://bugzilla.redhat.com/show_bug.cgi?id=1663554

**Comment by lukefromdc** [comment] 2019-01-04 21:36
Does someone here have a remote IR receiver set up on a computer to test this? I do not. @monsta @raveit65 ?

**Comment by tonyabc** [comment] 2019-01-04 22:31
@lukefromdc

Luke, are you in DC?

I have a friend in NY and am more then happy to ask him to buy something like a Dell remote and USB receiver (similar to my setup) and post them down to you.  They can be picked up on e-nay for circa $20

**Comment by lukefromdc** [comment] 2019-01-04 23:52
Fortunately, I am not the only person on this team

**Comment by tonyabc** [comment] 2019-01-05 00:55
@lukefromdc

OK, understand not wanting to give out address, but I didn't ask for your address, just if you're in DC.

The logistics of getting something to you doesn't require your address as I have friends in Bowie and Alexandria and I think me paying $20 for you to be able to look at this is a small price to pay.

Unfortunately I don't have another DE to be able to easily test this against, I may be able to find time next week to setup a specific dev machine to play with lots of the possible Kernel/OS/DE version control options that may be the underlying cause of this problem, but till then I can only try things out.

**Comment by lukefromdc** [comment] 2019-01-05 04:56
I just did some date checking, as you said this problem began at the end of November. It turns out the 1.20 (as opposed to the master/dev) branch of mate-settings-daemon (responsable for keymappings via the keybindings and media-keys (volume control etc) plugins didn't get any updates except translation updates and not using deprecation warnings in distcheck(used to generate tarballs and check for errors) since June 4  2018, whe  mate-settings-daemon 1.20.3 was released. there was not another point release (which your distro would pick up) all the way to December 23, 2018 when mate-settings-daemon 1.20.4 was released. Thus there is no way a November update to MATE would have changed this for the system as a whole unless you had not updated since June 4. 

A change in mate-control-center that broke something would not have changed any setting you already had working, so that can be ruled out and nothing else in MATE that I know of would even interact with this other than maybe mate-media not receiving a volume up/volume down command. Mate-media 1.20.1 came out in April 2018 and mate-media 1.20.2 came out on Dec 20, 2018, again with only translation-related updates. This I don't see any reasonable way MATE updates could have changed your situation. Dbus updates, kernel updates, etc are another matter.

No matter where the problem is however, if you know the date of the bad update and of the previous update, that will greatly narrow down finding the problem for whoever works on the code in question.
Do test another DE next week, but at this point I suspect the problem will continue no matter what DE you run-unless the problem is in dbus and ports to gdbus in GNOME (we are working on that with various programs in Master but none of this is going out the door in 1.20) avoided the issue by no longer using the old code and thus avoiding a bad update. That's a bit of conjecture on my part, but if this works in GNOME and not MATE that would be my guess. That would not mean there was a problem in MATE but rather in underlying code that GNOME has ported away from and we are also in the process of porting away from.

If you find the bad update, roll it back by reinstalling the older package, and watch the offered updates to that package in Federa for a fix for that bug. I've had to do that many times in Debian Unstable (where it is expected), so I always keep old package versions around.

**Comment by raveit65** [comment] 2019-01-05 10:32
Using infrared remotes are handled by `kernel-rc` or `LIRC - Linux Infrared Remote Control` packages, and not by any of our packages.
I am using `LIRC` for my `atiusbwonder` remote and all is working fine with fedora 28/29/rawhide.
I have already answered at redhat bugzilla report.
If you're using  `kernel-rc` config than something with the kernel is change and you need to adjust your config.
Using  infrared remote controls was never a simple task ;)
And very often a kernel change can break everything.
And all Mate packages have the same versions (1.20,x) in f28/29.
So your problem can't be caused by MATE.

Closing this in favor of downstream report at rhbz.

**Closed by raveit65** 2019-01-05 10:32 UTC

**Comment by tonyabc** [comment] 2019-01-05 10:38
@lukefromdc

I agree that I'm not 100% certain where the problem is originating from, that's why I put a question mark in the title of the original post.

What I can say with a reasonable degree of certainty after spending a while exploring this....

1.  It's very unlikely to be a kernel issue, else 'ir-keytable -t' output would not be working for all the buttons (and it does output all the buttons pressed on the remote with the matching mapping from my mce_rc6 file in /etc/rc_keymaps.  I even made some test changes to that file to ensure the data being presented by 'ir-keytable -t' matched the data I had in the file.

2.  It occurred to me that it was possible that only options that had been changed in /etc/rc_keymaps/mce_rc6 file (as against the default settings if you didn't use a file) were not being passed, unfortunately that isn't the case.

3.  When I finally came across the app 'key-mon' it confirmed what I suspected that NO data was getting passed to the DE when most of the buttons were pressed (as stated in the OP - having two terminal sessions open side by side with 'ir-keytable -t' running in one and 'key-mon' running in the other with it's GUI output sitting on 'top' of that terminal session. I can clearly see which buttons are fully working as a button press generates a response in both Terminal sessions simultaneously, whereas a 'not being passed' button only generates a response in the 'ir-keytable -t' terminal seesion).

I will go back once I've been able to setup a dev box and see if I can identify exactly which update broke it.....but that's going to take a few days at least.

Have a great weekend.

**Comment by tonyabc** [comment] 2019-01-05 10:48
@raveit65

Would it be possible for you to test on your setup without lirc but just kernel-rc?

Just a added note on the immediately previous comment to lukefromdc, in point 1 I say it's unlikely to be a kernel issue, I stand by that statement for the reasons given, however I cannot discount that something has changed in what data is passed for how it's  passed rom the kernel-rc to the DE.  What is somewhat confusing to me though is it's 'selectively' broken....some key presses do get passed while others do not.

As stated before I'll be setting up a specific dev box this week to try to backtrack exactly what has broken this as something has.

**Comment by raveit65** [comment] 2019-01-05 13:00
> Would it be possible for you to test on your setup without lirc but just kernel-rc?

@tonyabc 
yes, if you write a foolproof TODO for my `atiusbwonder` remote, which takes not more than 5min to use it :) 
I know nothing about how to use kernel-rc for a remote and i am very happy with my working lirc config.
And please let us use downstream rhbz report for this.

**Comment by tonyabc** [comment] 2019-01-06 15:31
@raveit

I wrote this 4 years ago when I switched from lirc to the kernel option, more then happy to help in any way I can if it's of any use to you.

http://lists.mythtv.org/pipermail/mythtv-users/2015-February/376311.html

**Comment by raveit65** [comment] 2019-01-06 16:05
@tonyabc 
What is so hard to post at https://bugzilla.redhat.com/show_bug.cgi?id=1663554  ?
It's me.
