### ISSUE TITLE
Window resizing problems!

### ISSUE THREAD

**Issue by nunatak** [mate-desktop/mate-desktop#225] opened 2016-05-13 09:57 UTC
Using the shortcut for fast resizing windows seems a bit buggy! Sometimes you can only resize it's width or height. Desirable is the diagonal resizing feature by clicking the shortcut. Before I switched to Mate recently, I used XFCE. There resizing works much better! 

Or is it wanted as it works right now?

**Comment by raveit65** [comment] 2016-05-13 10:57
Best way to resize a window is:
```
[rave@mother ~]$ gsettings get org.mate.Marco.general mouse-button-modifier
'<Alt>'
[rave@mother ~]$ gsettings get org.mate.Marco.general resize-with-right-button
true
```
Than use alt+right click anywhere in a window
Is this perfect enough for you? ;)

**Comment by monsta** [comment] 2016-05-13 11:18
Duplicate of https://github.com/mate-desktop/marco/issues/264 + wrong repository.

**Closed by monsta** 2016-05-13 11:18 UTC

**Comment by nunatak** [comment] 2016-05-19 18:03
@raveit65 Yeah! Pretty good! Thank you!

Sorry for duplicate!
