### ISSUE TITLE
Nvidia 495.46 is conflicting with Mate desktop and make Xorg crash

### ISSUE THREAD

**Issue by s3rg3** [mate-desktop/mate-desktop#505] opened 2021-12-29 18:40 UTC
Hello,

The lastest version of the 495 Nvidia branch seems to be conflicting with the mate desktop on multiple distributions (Fedora, Gentoo, Archlinux), i post it there in case someone is willing to investigate why and maybe have some Nvidia's contact to get in touch with.

#### Expected behaviour
Run startx and enjoy the Mate Desktop. 

#### Actual behaviour
Run startx and get Xorg crash not letting you enjoy the Mate desktop.

#### Steps to reproduce the behaviour
Install the Nvidia 495.46 driver and startx.

#### MATE general version
1.26.0

#### Package version
1.26.0-1

#### Linux Distribution
Archlinux

#### Link to bugreport of your Distribution (requirement)
https://bugs.archlinux.org/task/73031?project=1&string=nvidia
https://forums.developer.nvidia.com/t/495-46-xorg-sigsegv-in-fedora-35-only-on-msi-mpg-trident3-and-only-for-mate-desktop/199076
https://forums.developer.nvidia.com/t/x-server-1-21-1-1-crash-on-startx-with-nvidia-driver-495-46/198417

**Comment by raveit65** [comment] 2021-12-29 21:10
I can confirm this with fedora 34 with my gtx1650. But i think this is a nvidia driver problem.
nvidia-495.46 is selected with with download-type "new feature branch" for my card.
https://www.nvidia.com/Download/driverResults.aspx/184248/en-us
If i choose download-type "Produktion branch" nvidia pointed me to this driver 
https://www.nvidia.com/Download/driverResults.aspx/184163/en-us
After selecting 470xxx from rpmfusion everything works as normal ;)
```
[root@mother rave]# rpm -qa *nvidia*
xorg-x11-drv-nvidia-470xx-kmodsrc-470.94-1.fc34.x86_64
xorg-x11-drv-nvidia-470xx-libs-470.94-1.fc34.x86_64
akmod-nvidia-470xx-470.94-1.fc34.x86_64
nvidia-settings-470xx-470.94-1.fc34.x86_64
xorg-x11-drv-nvidia-470xx-470.94-1.fc34.x86_64
kmod-nvidia-470xx-470.94-1.fc34.x86_64
kmod-nvidia-470xx-5.15.11-100.fc34.x86_64-470.94-1.fc34.x86_64
[root@mother rave]#
```

**Comment by karlkleinpaste** [comment] 2021-12-29 21:28
I'm the author of the "only on MSI Trident" note at nvidia.com forums. My instance is F35, most recent 2 kernels.
I agree that it's not a MATE problem, but the bug is tickled by MATE (only), so it would be good if MATE folks could connect with nvidia to find cause & fix.
It's intriguing that, in my case, it affects only 1 brand of hardware, while my HPs are happy as can be with 495.46.

**Comment by s3rg3** [comment] 2022-01-01 12:51
No more crash with the Xorg-server patch from this issue:

https://gitlab.freedesktop.org/xorg/xserver/-/issues/1275

if Xorg-server is not patched desactivating Marco compositor also resolve the crash.

**Comment by raveit65** [comment] 2022-01-01 19:00
Cool, i think we can leave the report open a while, to inform users.

**Comment by Noobilite** [comment] 2022-01-03 20:22
Is this related to the problem?
[https://forums.developer.nvidia.com/t/495-46-xorg-sigsegv-in-fedora-35-only-on-msi-mpg-trident3-and-only-for-mate-desktop/199076/7](url)

> kfk
Dec 29

My stack trace at the top does include “present_event_notify” so it would seem that this is the problem. What confuses me, however, is that my HP Omen is not affected by this problem. I run MATE here as well.

Oh, now, hang on, wait just one darn second…

AHA!

dconf read /org/mate/desktop/session/required-components/windowmanager

Normally says “marco.”

I use compiz on my main machine, not marco. But I had never configured myself on the MSIs to stop using marco, because they’re kinda special case and largely remote use only (as I mentioned above, VNC + VGL). On the MSIs, I just now changed marco to compiz-manager, which is a wrapper script that does startup checks for necessary sanity, and poof no more crash of Xorg. Evidently compiz does not use “present.”

So, 2 things:

    Xorg needs a patch, sure, to avoid a crash when the window manager uses “present.”
    It appears that marco alone uses it. If e.g. gnome-shell used it, Xorg would die in GNOME, too, but doesn’t. compiz must not use it.

Has this problem arisen because 495.46 has new support for “present” so that marco inadvertently finds it and tickles the bug?

**Comment by karlkleinpaste** [comment] 2022-01-03 20:29
It's not strictly marco's fault, it's the fault of Xorg in not handling what marco legitimately did. So... nothing to be done in MATE.

That's my understanding so far, anyway.

**Comment by adatum** [comment] 2022-02-01 21:45
For Fedora this issue addressed by https://bugzilla.redhat.com/show_bug.cgi?id=2046147 and solved with xorg-x11-server-1.20.14-3 https://bodhi.fedoraproject.org/updates/FEDORA-2022-a2017f20aa

**Comment by dadie11** [comment] 2022-05-15 12:51
Good afternoon. First of all, a great big 'thank-you' to the - very often - forgotten heroes who take the time to resolve all the often extremely technical problems for those who are less capable. 

I would like to add my tale of woe to this thread of having a perfectly capable Mint20.3 MATE system reducing  it's user to various states of apoplexy in being unable to resolve this inability of having an nVidia drive working properly with my recently upgraded MoBo from a B550M to an X570M and back to the B550. 
As an aside, the then current kernel (5.4.0-39 as well as all subsequent versions, as far as I can make-out) also complicated matters by not recognising the ethernet port...XID641...which I was able to resolve - again -  thanks to an unsung hero.

Once the system is installed and after updating to the latest nVidia driver...(510 if memory permits)...on re-booting goes to the 'Lock screen' and I am unable to go any further. So I am just sticking with the 'nouveau' driver for now, which at least works...just. I have yet to try various patches I have seen, because of time constraints.

I have a Ryzen 3700x on the aforementioned Msi B550M Mortar WiFi, GTX3060, and 128gb of Patriot Viper PC4-28800 running under Mint 20.2

**Comment by lukefromdc** [comment] 2022-05-15 15:16
Note that we may get less of this one in the future. Due apparently to data centers objecting to kernel taint, Nvidia is releasing a true open source kernel driver for their video cards. The closed drivers for the newer cards will use it-anf Nouveau probably will also be able to. That should end the firmware/no reclocking issue and eventually make Nouveau competitive.

This is essentially what AMD did with AMDGPU, and we can thank data centers using CUDA, unable to submit kernel bug reports due to kernel taint, and finding Nvidia to be their only blob driver for thid

Preaumably they will move the stuff they want to keep secret to either firmware (which they will have to actually distribute now w the FOSS driver) or to the closed userspace model.

**Comment by raveit65** [comment] 2022-08-06 14:30
This is fixed by xorg-server.

**Closed by raveit65** 2022-08-06 14:30 UTC
