### ISSUE TITLE
Mate screenshot disable with compiz or emerald

### ISSUE THREAD

**Issue by leinfeva** [mate-desktop/mate-desktop#185] opened 2015-07-19 03:42 UTC
Hi all, I've installed F23 with Mate desktop 1.10.1 and all work fine, but key "Print" is disable if mate-compiz or mate-emerald is enabled . the only way that fix this is using the keyboard shortcuts.

Some ideas ? 

Thanks Team !!

Additional info:
[leinfeva@new-host-5 ~]$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Bay Trail 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.7.0-devel (git-ea633db)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.7.0-devel (git-ea633db)
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.7.0-devel (git-ea633db)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
[leinfeva@new-host-5 ~]$

**Comment by NiceandGently** [comment] 2015-07-19 14:50
Hi, currently i haven't installed f23 on bare metal to test this, it's bit early to do that for me.
Maybe  a rebuild of compiz is needed against mate-1.10, which will happen shortly before alpha release.
At the moment this doesn't make any sense because 'all' can change in this early dev state of f23 ;)

**Comment by NiceandGently** [comment] 2015-07-19 15:31
Ok, confirmed in a VM with poor performance for compiz.
But i changed the key in ccsm mate-compat plugin to crtl-alt-p and screenshot is working.
Than i change it back to normal print key.....and screenshot is working :dancers:  
Does this work you?

**Comment by leinfeva** [comment] 2015-07-19 21:19
@NiceandGently Yes, this work also other way that enable the key is editing the shortcuts and add "mate-screenshot -d 1" to the print key.

Also case similar is the "alt +f2" by default is enable, but with compiz or emerald is not work the only way for activate this is using the ccsm and enable "mate compatibility" .

All work now. Thank so much !!!!!

**Comment by NiceandGently** [comment] 2015-07-19 21:44
@leinfeva 
cool, that it works.
.......and yes this is the signification of the mate compat plugin.
Can you please close this report, i don't have the rights to do that.

**Closed** 2015-07-19 21:48 UTC
