### ISSUE TITLE
x86_32 support

### ISSUE THREAD

**Issue by alxpl** [mate-desktop/mate-desktop#289] opened 2017-09-07 01:26 UTC
Hello,

I am writing on behalf of the Fedora x86 SIG, which is currently under formation. Our goal is to keep Fedora running on the i686 platform and if there is enough interest, we might produce an i686 spin. As we are examining our options for a specific deliverable that we want to see maintained, the “tiny server” target seems the most sustainable one, but we haven't ruled out desktops yet.

What I would like to hear from you is if your road map for the foreseeable future includes some change that might make it impractical to run MATE on i686 machines (is the migration to gtk3 such a change?), or if you intend to drop support for the architecture altogether. We haven't decided on the minimum specs we are willing to support/test, but for now PAE support seems out and we are still trying to figure out if we want to include non-SSE2 CPUs. In any case, we are talking about systems with limited resources, so it would be desirable e.g. to keep RAM use of the desktop below 512MB.

Best regards
Alexander Ploumistos

**Comment by raveit65** [comment] 2017-09-07 05:39
I don't really understand why i should support cpus from 10-15 years ago as  fedora maintainer.
Normal cpus can be used  with normal x86_64 arch, and where can you buy a new box with 500 MB ram ?
And i see a lot of bugs which i can't reproduce with x86_64 boxes.
I invited you to  become member of of  alt-gtk-de-sig group "Alternative GTK desktop environments", to support MATE as maintainer for those arch and working on related bug reports.
I am happy to sponsor you as a package maintainer.
Honestly, i like the idea that fedora want to drop support for i686, as we will have less reports which will reduce my workload.

**Comment by alxpl** [comment] 2017-09-07 14:28
> I don't really understand why i should support cpus from 10-15 years ago as fedora maintainer.

You *shouldn't*, one of the SIG's tasks would be to work with upstream developers and downstream packagers in dealing with 32-bit-specific issues. Since you are both up and down the stream 🙂, things should be simpler.

There are a number of use cases and reasons for keeping the arch around for as long as possible, I'll give you one of mine: As part of my job, I've had to walk for 2 hours in the snow, at 1500m altitude, to get to a misbehaving link, while carrying a toolbox, supplies and my old Atom netbook. I would love to have a newer, lighter ultrabook, but a) I can't afford one and b) I would also need to carry a bunch of converters and cables to interface with the machinery, as newer computers tend to forgo a number of "legacy" ports. That netbook runs F25 with MATE, and at boot, with all the services, applets, bells and whistles I have running, consumes just 360MB of RAM out of the total 1.5GB.

> Normal cpus can be used with normal x86_64 arch, and where can you buy a new box with 500 MB ram ?

You are right, you can't. Though I'm sure you've noticed that starting with F27, we have a number of "non-normal" architectures that we need to support, some of which are release blocking. In theory, if your packages have issues on one of these, you open a bug report against an ExcludeArch blocker bug and the corresponding SIG should help you deal with them. Even more so, now that i686 has been demoted to a secondary arch. By the way, have you had any such experience?

> And i see a lot of bugs which i can't reproduce with x86_64 boxes.

That onus would be upon the SIG members.

> I invited you to become member of of alt-gtk-de-sig group "Alternative GTK desktop environments", to support MATE as maintainer for those arch and working on related bug reports.
> I am happy to sponsor you as a package maintainer.

I know how hard it is for you to deal with development, packaging, spins and bug reports all by yourself and we've discussed this in the past. I have filed bug reports against MATE components in Fedora and whenever I could, I helped with testing/troubleshooting. Unfortunately, spare time is a luxury I don't often come by. I try to maintain my packages with due diligence, but I am also stretched thin; I can't fully commit to the i686 SIG (or any other SIG for that matter), but I can help with specific issues and that's what I am offering. Heck, I've had a couple of packages ready for review for the past month, but I haven't had the time to file review requests yet.

All that being said, the x86 SIG has only had a single meeting so far and its future is uncertain. I would still like to know if there is an upcoming change in MATE that would negatively impact i686, so that I have something to report back and the rest of the people can examine their options.

Best regards

**Comment by monsta** [comment] 2017-09-18 15:11
Do we really have something platform-specific here upstream?

**Comment by monsta** [comment] 2017-10-01 18:24
@raveit65: what should we do about it? Seems Fedora-specific to me.

**Comment by raveit65** [comment] 2017-10-01 19:38
Well, fedora isn't the only main distro which use i686 and x86_64 libs, ie. OpenSuse.
And i guess Gentoo and his derivates will make a difference too, not sure about.
I can only speak for myself,
a) i don't have any plans to drop i686 support,
b) what is specific needed for i686?
c) all this can only be handle with specific issues for bugs with i686

**Comment by alxpl** [comment] 2017-10-02 00:17
> I can only speak for myself,
> a) i don't have any plans to drop i686 support,

That is good to know.
> b) what is specific needed for i686?

Dependencies that require specific CPU instruction sets, particularly SSE2 and later stuff. I don't know if MATE has any such dependencies though. Someone suggested that the migration to gtk3 *might* introduce issues, but I really have no idea.
> c) all this can only be handle with specific issues for bugs with i686

If there is anything i686-specific that you need tested on actual hardware, a lot of people have οffered their relics for testing. Just ask on the [x86 mailing list](https://lists.fedoraproject.org/archives/list/x86@lists.fedoraproject.org/). There is also [this tracker bug](https://bugzilla.redhat.com/show_bug.cgi?id=1489998).

**Comment by monsta** [comment] 2017-10-23 13:07
> Dependencies that require specific CPU instruction sets, particularly SSE2 and later stuff. I don't know if MATE has any such dependencies though.

I can't remember anything like that here. Maybe some distros have that in some packages, but that's done by the maintainers.

**Comment by raveit65** [comment] 2017-10-23 20:24
so closing it.
feel free to file out a specific report if there is a problem.

**Closed** 2017-10-23 20:26 UTC

**Comment by alxpl** [comment] 2017-10-23 20:27
Sure, will do.
Thank you both.
