### ISSUE TITLE
File selection dialog path textbox

### ISSUE THREAD

**Issue by meiskam** [mate-desktop/mate-desktop#540] opened 2022-11-18 10:34 UTC
#### Expected behaviour
Set dconf org.gtk.settings.file-chooser.location-mode to 'filename-entry'
Click 'Open' in Pluma, have a place to type the location of a file

#### Actual behaviour
Click 'Open' in Pluma, have to click folders and breadcrumbs to find file

#### Steps to reproduce the behaviour
$ dconf write /org/gtk/settings/file-chooser/location-mode "'filename-entry'"
$ dconf watch /org/gtk/settings/file-chooser/location-mode

open Pluma, click 'Open', click 'Cancel'

notice dconf value has changed

    /org/gtk/settings/file-chooser/location-mode
    'path-bar'

#### MATE general version
MATE Desktop Environment 1.26.0

#### Package version
gtk version 3.24.33

#### Linux Distribution
Ubuntu MATE 22.04.1 LTS (Jammy Jellyfish)

#### Link to bugreport of your Distribution (requirement)
https://ubuntu-mate.community/t/file-selection-dialog-path-textbox/26089

#### Note
I couldn't find mate's fork of the gtk version from gnome 2, please point me in the right direction if this isn't the right place to post this

**Comment by cwendling** [comment] 2022-11-22 09:23
> I couldn't find mate's fork of the gtk version from gnome 2, please point me in the right direction if this isn't the right place to post this

MATE has no GTK fork, it uses whatever GTK3 library you have.  Also, I can reproduce this without any specific MATE components involved.

This seems to be an issue (or not) with GTK3 itself, if I grep the code quickly, it never actually *reads* that setting, it only writes it.  It seems to date back to https://gitlab.gnome.org/GNOME/gtk/-/commit/5c42068bb3277b2a33bfdaca1fa21f2d96f4706c.
I'm closing this, as it seems to be related to GTK only, feel free to report there (or explain why we should reopen this here)

**Closed by cwendling** 2022-11-22 09:23 UTC
