### ISSUE TITLE
Panel Shadow Not Initially Shown

### ISSUE THREAD

**Issue by kmcn1875** [mate-desktop/mate-desktop#173] opened 2015-06-09 13:58 UTC
When I initially login to MATE, the panel shadow is not shown. To make the shadow visible, I need to open MATE Tweak and make a change to one of the Compositing Settings.

To recreate: 

1) Set Window Manager to Marco
2) Choose 'Use Compositing'
3) Log out then log back in
    ---- Panel Shadow not visible
4) Open MATE Tweak - Windows
5) De-select 'Use Compositing'
6) Re-select 'Use Compositing'
    ---- Panel Shadow is now visible

**Comment by kmcn1875** [comment] 2015-06-09 14:02
![panel_1](https://cloud.githubusercontent.com/assets/8049253/8059547/e4ca6328-0ec0-11e5-9905-d4a23a9ea1a7.png)

![panel_2](https://cloud.githubusercontent.com/assets/8049253/8059553/ec690c4c-0ec0-11e5-9d10-2c222e11b12b.png)

**Comment by stefano-k** [comment] 2015-06-12 07:41
Duplicate of https://github.com/mate-desktop/mate-panel/issues/193

**Closed by stefano-k** 2015-06-12 07:41 UTC
